def on_button_pressed_a():
    basic.show_number(input.temperature())
input.on_button_pressed(Button.A, on_button_pressed_a)

def on_forever():
    if input.light_level() < 50:
        music.set_tempo(130)
        music.play_tone(370, music.beat(BeatFraction.WHOLE))
        music.play_tone(330, music.beat(BeatFraction.DOUBLE))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        music.play_tone(330, music.beat(BeatFraction.WHOLE))
        music.play_tone(294, music.beat(BeatFraction.WHOLE))
        music.play_tone(277, music.beat(BeatFraction.WHOLE))
        music.play_tone(294, music.beat(BeatFraction.WHOLE))
        music.play_tone(330, music.beat(BeatFraction.WHOLE))
        music.play_tone(370, music.beat(BeatFraction.DOUBLE))
        music.play_tone(494, music.beat(BeatFraction.DOUBLE))
        music.play_tone(554, music.beat(BeatFraction.WHOLE))
        music.play_tone(587, music.beat(BeatFraction.WHOLE))
        music.play_tone(659, music.beat(BeatFraction.WHOLE))
        music.play_tone(587, music.beat(BeatFraction.WHOLE))
        music.play_tone(554, music.beat(BeatFraction.WHOLE))
        music.play_tone(880, music.beat(BeatFraction.WHOLE))
        music.play_tone(784, music.beat(BeatFraction.WHOLE))
        music.play_tone(740, music.beat(BeatFraction.DOUBLE))
        music.play_tone(370, music.beat(BeatFraction.WHOLE))
        music.play_tone(294, music.beat(BeatFraction.WHOLE))
        music.play_tone(330, music.beat(BeatFraction.WHOLE))
        music.play_tone(349, music.beat(BeatFraction.WHOLE))
        basic.show_string("Esta escuro")
basic.forever(on_forever)
